### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by bean07** [GustavGenberg/agarplus-iplist#2]
http://imgur.com/LMJT8no

**Comment by GustavGenberg** [comment]
This is the cause of a client who's not sending enough data... 

It tries to replace some data that doesn't exists...

**Comment by bean07** [comment]
Thanks

2016-06-10 2:16 GMT+07:00 Gustav Genberg <notifications@github.com>:

**Comment by bean07** [comment]
-close this pls
